### ISSUE TITLE
Building on 18.04 + kernel 4.3 or newer

### ISSUE THREAD

**Issue by gsedej** [electrified/asus-wmi-sensors#53]
Hello,

I would like to note, if someone else has issues...
The module does not build on ubuntu 18.04 when using newer kernels (e.g. installed via ukuu)

Like module zenpower, installing gcc8 or modifinig some files you can build it.

https://github.com/ocerman/zenpower/issues/23

**Comment by electrified** [comment]
If you use ukuu, or any other method to install a kernel, you should use the version of GCC used to build the kernel to build any additional out-of-tree modules otherwise you may run into issues.

Check `cat /proc/version` to see the version of GCC used to build the kernel.

Others have had this issue before, see https://github.com/electrified/asus-wmi-sensors/issues/44 so I might add something to the readme....
